### ISSUE TITLE
plagin load settings from Json

### ISSUE THREAD

**Issue by YukiMiyatake** [YukiMiyatake/GOSICK#5]

**Comment by YukiMiyatake** [comment]
JSONの設定をよみこみ loadPlugin  を行う

**Comment by YukiMiyatake** [comment]
main.go、cmd_main.go　にて
	lib.LoadPlugin(&mention, "memo", "plugins/memo/memo.so")
など　プラグイン読み込みをコードに埋めてるのをJSONで指定できるようにしたい
第一引数はいまのところ &mention限定でいい（設計考える・・）
第二引数は String配列で。
第三引数は ファイルパス

**Comment by ryo-ohnishi** [comment]
LoadPluginするときは第一引数に&mentionと第二引数にプラグインの名前を指定し
LoadPluginのメソッド側でjsonから名前をもとにパスを取得するようにしています。
